# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"

  # すべてのマシンで同じ鍵を使う
  config.ssh.insert_key = false

  config.vm.define "vag1" do | vag |
    vag.vm.box = "ubuntu/xenial64"
    vag.vm.network "forwarded_port", guest: 80, host: 8080
    vag.vm.network "forwarded_port", guest: 443, host: 8443
  end
  config.vm.define "vag2" do | vag |
    vag.vm.box = "ubuntu/xenial64"
    vag.vm.network "forwarded_port", guest: 80, host: 8081
    vag.vm.network "forwarded_port", guest: 443, host: 8444
  end
  config.vm.define "vag3" do | vag |
    vag.vm.box = "ubuntu/xenial64"
    vag.vm.network "forwarded_port", guest: 80, host: 8082
    vag.vm.network "forwarded_port", guest: 443, host: 8445
  end

end
