---
- name: print out operating system
  hosts: server1
  gather_facts: True
  tasks:
    - debug: var=ansible_distribution

    - name: print ansible_local
      debug: var=ansible_local

    - name: print book title
      debug: msg="The title of the book is {{ ansible_local.example.book.title }}"
