- name: sample variable definitions outside of yaml
  hosts: vag1
  vars_files:
    - variables.yml

  tasks:
    # - name: capture output of whoami command
    #   command: whoami
    #   register: login
    
    - name: capture output of id command
      command: id -un
      register: login
    - debug: var=login
    - debug: msg="Logged in as user {{ login.stdout }}"
