# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # すべてのマシンで同じ鍵を使う
  config.ssh.insert_key = false

  ["server1", "server2"].each do |each|
    config.vm.define each do | vag |
      vag.vm.box = "ubuntu/xenial64"
    end
  end
end
