---
- hosts: web-server
  user: vagrant
  vars:
    test_dir: test
    work_dir: /home/vagrant/{{ test_dir }}
  tasks:
    - name: create directory test
      file: path={{ test_dir }} state=directory

    - name: download pip
      get_url: url=https://bootstrap.pypa.io/get-pip.py
               dest=~/get-pip.py force=True

    - name: install pip
      become: yes
      command: python get-pip.py

    - name: install virtualenv
      become: yes
      command: pip install virtualenv



